name: grove
description: A Dart library package for interfacing to the Grove range of sensors
version: 1.0.0
author: Steve Hamblett <steve.hamblett@linux.com>
homepage: https://github.com/shamblett/grove

environment:
 sdk: ">=2.6.0  <3.0.0"

dependencies:
 ffi: '^0.1.3-dev.3'
 mraa: '^1.0.0'

dev_dependencies:
 test: '^1.9.3'
 mockito: '^4.1.1'
 
 

