name: grove
description: A Dart library package for interfacing to the Grove range of devices
version: 3.0.0
homepage: https://github.com/shamblett/grove

environment:
 sdk: '>=2.12.0 <3.0.0'

dependencies:
 ffi: '^1.0.0'
 mraa: '^2.0.0'
 meta: '^1.3.0'
 collection: '^1.15.0'

dev_dependencies:
 test: "^1.16.8"
 pedantic: "^1.11.0"
 mockito: '^5.0.3'
 
 

