name: grove
description: A Dart library package for interfacing to the Grove range of devices
version: 4.0.2
repository: https://github.com/shamblett/grove
homepage: https://github.com/shamblett/grove

funding:
 - https://www.darticulate.com/#funding

environment:
 sdk: '>=3.7.0 <4.0.0'

dependencies:
 ffi: '^2.1.4'
 mraa: '^4.0.2'
 meta: '^1.17.0'
 collection: '^1.19.1'

dev_dependencies:
 test: '^1.26.2'
 lints: '^6.0.0'
 mocktail: '^1.0.4'
 dart_code_metrics_presets: '^2.22.0'
 
 

