name: grove
description: A Dart library package for interfacing to the Grove range of devices
version: 4.0.0
repository: https://github.com/shamblett/grove
homepage: https://github.com/shamblett/grove

funding:
 - https://www.darticulate.com/#funding

environment:
 sdk: '>=3.0.0 <4.0.0'

dependencies:
 ffi: '^2.0.2'
 mraa: '^4.0.0'
 meta: '^1.9.1'
 collection: '^1.17.2'

dev_dependencies:
 test: '^1.24.2'
 lints: '^2.1.0'
 mocktail: '^0.3.0'
 
 

