name: grove
description: A Dart library package for interfacing to the Grove range of devices
version: 2.0.0
homepage: https://github.com/shamblett/grove

environment:
 sdk: ">=2.7.0  <3.0.0"

dependencies:
 ffi: '^0.1.3'
 mraa: '^1.3.0'
 meta: '^1.2.3'
 collection: '^1.14.13'

dev_dependencies:
 test: "^1.14.2"
 pana: "^0.13.5"
 pedantic: "^1.9.0"
 mockito: '^4.1.1'
 
 

