name: grove
description: A Dart library package for interfacing to the Grove range of devices
version: 3.1.0
repository: https://github.com/shamblett/grove
homepage: https://github.com/shamblett/grove

funding:
 - https://www.darticulate.com/#funding

environment:
 sdk: '>=2.17.0 <3.0.0'

dependencies:
 ffi: '^2.0.1'
 mraa: '^3.0.0'
 meta: '^1.3.0'
 collection: '^1.15.0'

dev_dependencies:
 test: '^1.21.5'
 lints: '^2.0.0'
 mocktail: '^0.3.0'
 
 

