name: grove
description: A Dart library package for interfacing to the Grove range of devices
version: 4.0.1
repository: https://github.com/shamblett/grove
homepage: https://github.com/shamblett/grove

funding:
 - https://www.darticulate.com/#funding

environment:
 sdk: '>=3.0.0 <4.0.0'

dependencies:
 ffi: '^2.1.0'
 mraa: '^4.0.2'
 meta: '^1.11.0'
 collection: '^1.18.0'

dev_dependencies:
 test: '^1.25.0'
 lints: '^3.0.0'
 mocktail: '^1.0.2'
 
 

